### ISSUE TITLE
docker部署m3e-large-api无法启动

### ISSUE THREAD

**Issue by hemaniu** [gzyunke/test-docker#4]
老师，请问m3e-large-api启动一会就报错了。

以下是logs：
2024-01-11 16:00:34 No sentence-transformers model found with name ./moka-ai_m3e-large. Creating a new one with MEAN pooling.
2024-01-11 16:00:37 Traceback (most recent call last):
2024-01-11 16:00:37   File "/usr/local/bin/uvicorn", line 8, in <module>
2024-01-11 16:00:37     sys.exit(main())
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
2024-01-11 16:00:37     return self.main(*args, **kwargs)
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
2024-01-11 16:00:37     rv = self.invoke(ctx)
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
2024-01-11 16:00:37     return ctx.invoke(self.callback, **ctx.params)
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
2024-01-11 16:00:37     return __callback(*args, **kwargs)
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 416, in main
2024-01-11 16:00:37     run(
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 587, in run
2024-01-11 16:00:37     server.run()
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
2024-01-11 16:00:37     return asyncio.run(self.serve(sockets=sockets))
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
2024-01-11 16:00:37     return loop.run_until_complete(main)
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2024-01-11 16:00:37     return future.result()
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
2024-01-11 16:00:37     config.load()
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/site-packages/uvicorn/config.py", line 467, in load
2024-01-11 16:00:37     self.loaded_app = import_from_string(self.app)
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
2024-01-11 16:00:37     module = importlib.import_module(module_str)
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
2024-01-11 16:00:37     return _bootstrap._gcd_import(name[level:], package, level)
2024-01-11 16:00:37   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2024-01-11 16:00:37   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2024-01-11 16:00:37   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2024-01-11 16:00:37   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2024-01-11 16:00:37   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2024-01-11 16:00:37   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2024-01-11 16:00:37   File "/app/localembedding.py", line 42, in <module>
2024-01-11 16:00:37     class ChatMessage(BaseModel):
2024-01-11 16:00:37   File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
2024-01-11 16:00:37   File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
2024-01-11 16:00:37   File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
2024-01-11 16:00:37   File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
2024-01-11 16:00:37   File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
2024-01-11 16:00:37   File "/usr/local/lib/python3.8/typing.py", line 774, in __subclasscheck__
2024-01-11 16:00:37     return issubclass(cls, self.__origin__)
2024-01-11 16:00:37 TypeError: issubclass() arg 1 must be a class

![image](https://github.com/gzyunke/test-docker/assets/144437525/caf2d7d0-8554-4a25-9b33-bf0a0c932f8e)

**Comment by gzyunke** [comment]
你这种是业务逻辑相关的，跟docker没关，跟你用的这个库相关，我没用过你这个
