### ISSUE TITLE
使用别人写好的Dockerfile时报错

### ISSUE THREAD

**Issue by UCAS-WUHU111** [gzyunke/test-docker#7]
Dockerfile内容如下：
```
# hash:sha256:e97af9bf49a7a886eee81509ac11dd1401a9a255bbf4e1dd79b6ae955a0850f7
FROM registry.codeocean.com/codeocean/miniconda3:4.9.2-cuda11.7.0-cudnn8-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN conda install -y --channel=pytorch \
        cudatoolkit==11.3.1 \
        h5py==3.7.0 \
        python==3.9.15 \
        pytorch==1.11.0 \
        tensorflow==2.5.0 \
        tqdm==4.64.1 \
    && conda clean -ya

RUN pip3 install -U --no-cache-dir \
    matplotlib==3.6.2

COPY postInstall /
RUN /postInstall
```
报错如下：
```
Traceback (most recent call last):
File "/opt/conda/lib/python3.9/site-packages/conda/exception_handler.py", line 17, in __call__
return func(*args, **kwargs)
File "/opt/conda/lib/python3.9/site-packages/conda/cli/main.py", line 54, in main_subshell
parser = generate_parser(add_help=True)
File "/opt/conda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 115, in generate_parser
configure_parser_create(sub_parsers)
File "/opt/conda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 767, in configure_parser_create
add_parser_solver(solver_mode_options)
File "/opt/conda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 1975, in add_parser_solver
solver.name for solver in context.plugin_manager.get_hook_results("solvers")
File "/opt/conda/lib/python3.9/site-packages/conda/base/context.py", line 492, in plugin_manager
from ..plugins.manager import get_plugin_manager
File "/opt/conda/lib/python3.9/site-packages/conda/plugins/__init__.py", line 28, in <module>
from .hookspec import hookimpl  # noqa: F401
File "/opt/conda/lib/python3.9/site-packages/conda/plugins/hookspec.py", line 16, in <module>
from .types import (
File "/opt/conda/lib/python3.9/site-packages/conda/plugins/types.py", line 15, in <module>
from ..core.solve import Solver
File "/opt/conda/lib/python3.9/site-packages/conda/core/solve.py", line 30, in <module>
from ..exceptions import (
File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 16, in <module>
from requests.exceptions import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' (/opt/conda/lib/python3.9/site-packages/requests/exceptions.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/conda/bin/conda", line 13, in <module>
sys.exit(main())
File "/opt/conda/lib/python3.9/site-packages/conda/cli/main.py", line 109, in main
return conda_exception_handler(main, *args, **kwargs)
File "/opt/conda/lib/python3.9/site-packages/conda/exception_handler.py", line 389, in conda_exception_handler
return_value = exception_handler(func, *args, **kwargs)
File "/opt/conda/lib/python3.9/site-packages/conda/exception_handler.py", line 20, in __call__
return self.handle_exception(exc_val, exc_tb)
File "/opt/conda/lib/python3.9/site-packages/conda/exception_handler.py", line 52, in handle_exception
from .exceptions import (
File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 16, in <module>
from requests.exceptions import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' (/opt/conda/lib/python3.9/site-packages/requests/exceptions.py)
```

**Comment by gzyunke** [comment]
这属于代码部分报错了，你可以进入容器中执行对应的命令去看能否跑成功，容器里面能跑成功了再写成dockerfile
